# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Драпак С.Н.

Группа: 317

In [1]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [8]:
l = [i for i in range(101) if (i % 7 == 0) & (i % 5 != 0)]
l

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [2]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [24]:
def sort_tokens(s):
    l = s.split(',')
    l = sorted(l)
    s = ','.join(l)
    return s

s1 = "cc,bb,aa"
s2 = "MSU,MIPT,HSE"
s3 = "z,y,x,w,v,u"

#sort_tokens(s1)
sort_tokens(s2)
#sort_tokens(s3)

'HSE,MIPT,MSU'

#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [30]:
def remove_duplicates(a):
    s = set(a)
    l = list(s)
    l = sorted(l)
    return l

l1 = [3,3,3,2,2,2,1,1,1,1]
l2 = ["CMC", "DCAM", "DIHT", "DCS", "CMC", "DCAM", "DIHT", "DCS"]
l3 = [1.1, 5.5, 3.3, 4.4, 1.1]

remove_duplicates(l2)
    

['CMC', 'DCAM', 'DCS', 'DIHT']

#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [155]:
map(lambda x: x.lower(), ["abCDefg", "HIjkL"])

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [156]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [157]:
from collections import defaultdict
d = defaultdict(int)
print d
d['abc'] += 1
print d
d['xxx']
print d

defaultdict(<type 'int'>, {})
defaultdict(<type 'int'>, {'abc': 1})
defaultdict(<type 'int'>, {'xxx': 0, 'abc': 1})


In [5]:
from collections import defaultdict

def words_count(texts):
    l = map(lambda x: x.split(' '), texts)
    l = reduce(lambda x, y: x + y, l)
    d = defaultdict(int)
    for w in l:
        d[w] += 1
    print d

text = ["aa bb cc ff aa", "aa bb ee ff dd"]
words_count(text)


defaultdict(<type 'int'>, {'aa': 3, 'bb': 2, 'cc': 1, 'dd': 1, 'ee': 1, 'ff': 2})


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [162]:
from urllib import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [163]:
raw_text[1000:1100]

u'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [217]:
import re
words = re.split('\W+', raw_text)
words = map(lambda x: x.lower(), words)
words = filter(lambda x: len(x) > 0, words)
dct = defaultdict(int)
for w in words:
    dct[w] += 1

sorted_keys = sorted(dct, lambda x, y: cmp(int(dct[x]), int(dct[y])), reverse = True)
popular = sorted_keys[0:20] #20 самыйх популярных
one_time_met = sorted_keys[-21:] # 20 встречающихся 1 раз





[u'lawful',
 u'this_',
 u'fawning',
 u'sabre',
 u'noxious',
 u'faithfully',
 u'uncontrollable',
 u'funds',
 u'deuce',
 u'tactics',
 u'rigamarole',
 u'venetian',
 u'rickety',
 u'unfolding',
 u'gnawing',
 u'bombarding',
 u'transfigured',
 u'june',
 u'upwards',
 u'sash',
 u'bereaved']

## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

Object `ones` not found.


In [50]:
import numpy as np
from numpy import random

N = 1000
max_values = np.zeros(N)
for i in range(N):
    m1 = random.normal(0, 1, size = (10,10))
    m2 = random.normal(0, 1, size = (10,10))
    mult = m1.dot(m2)
    max_values[i] = np.max(mult)

np.mean(max_values)
np.percentile(a = max_values, q = 95)



11.845450179919638

#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [65]:
b = random.poisson(lam = 5.0, size = 1000)
res = np.bincount(b)
res

array([  6,  35,  90, 148, 189, 162, 152,  96,  57,  42,  12,   4,   4,
         2,   1])

#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [68]:
def my_repeat(a):
    nums = np.array(range(len(a)))
    rep_res = np.repeat(nums, a)
    return rep_res

a = np.array([5,4,3,2,1])
my_repeat(res)

array([ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [79]:
def scale(X):
    med = np.mean(X, axis = 0)
    X = X - med
    sd = np.std(X, axis = 0)
    sd[sd == 0] = 1
    X = X / sd
    return X

test1 = [[1,2,3,4],[2,3,4,5],[3,4,5,6]]
test2 = random.rand(5, 10)
test3 = [[1,3,4,5],[1,2,3,4]]
print(np.std(scale(test3), axis = 0))
print(np.mean(scale(test3), axis = 0))

[ 0.  1.  1.  1.]
[ 0.  0.  0.  0.]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [29]:
a = np.random.normal(10,1,(5,5))
det = np.linalg.det(a)
tr = np.trace(a)
min_a = np.min(a)
max_a = np.max(a)
U, s, V = np.linalg.svd(a)
spectral_norm = s[0]
frob = np.linalg.norm(a, ord = "fro")
eig_val, v = np.linalg.eig(a)
p_inv = np.linalg.pinv(a)

## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [2]:
data = pd.read_csv("2008.csv")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7009728 entries, 0 to 7009727
Data columns (total 29 columns):
Year                 int64
Month                int64
DayofMonth           int64
DayOfWeek            int64
DepTime              float64
CRSDepTime           int64
ArrTime              float64
CRSArrTime           int64
UniqueCarrier        object
FlightNum            int64
TailNum              object
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin               object
Dest                 object
Distance             int64
TaxiIn               float64
TaxiOut              float64
Cancelled            int64
CancellationCode     object
Diverted             int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtypes: float64(14), int64(10), object(5)
memory usage: 1.6+ GB


In [14]:
CC = data['CancellationCode'].copy()

In [21]:
sum(CC == 'B')

54904

In [23]:
#54904 B - Погода стала самой частой причиной отмены рейса


In [25]:
np.max(data['Distance']) #Максимум

4962L

In [26]:
np.min(data['Distance']) #Минимум

11L

In [27]:
np.mean(data['Distance']) #Средние

726.3870294253928

In [28]:
suspicious = data[data['Distance'] == 11L]

In [29]:
suspicious #В мае и Августе 15 и 10 числа соответственно (среда и суббота, рейсы 4988, 5572)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
2547298  2008      5          15          4     2037        1800     2125   
4392215  2008      8          10          7     1315        1220     1415   

         CRSArrTime UniqueCarrier  FlightNum        ...         TaxiIn  \
2547298        1900            OH       4988        ...             10   
4392215        1320            OH       5572        ...              8   

         TaxiOut  Cancelled  CancellationCode  Diverted  CarrierDelay  \
2547298        7          0               NaN         0           145   
4392215       38          0               NaN         0            55   

        WeatherDelay NASDelay  SecurityDelay  LateAircraftDelay  
2547298            0        0              0                  0  
4392215            0        0              0                  0  

[2 rows x 29 columns]

In [39]:
susp_FN_0 = 4988
susp_FN_1 = 5572

In [44]:
fl1 = data[(data['FlightNum'] == susp_FN_0) & (data['UniqueCarrier'] == 'OH')] 

In [45]:
fl1['Distance']
fl1[fl1['Distance'] != 834]['Distance']
# И того, для первого рейса в большую часть дней пролетал 834 мили и еще в один день 96

1941154    96
2547298    11
Name: Distance, dtype: int64

In [46]:
fl2 = data[(data['FlightNum'] == susp_FN_1) & (data['UniqueCarrier'] == 'OH')]

In [47]:
fl2[fl2['Distance'] != 544]['Distance']
#Второй во все остальные дни пролетел 544 Мили

4392215    11
Name: Distance, dtype: int64

In [74]:
#for a in data['Origin']:
    #ap_dct[a] += 1
    
from collections import Counter
b = Counter(data['Origin'])
b.most_common(1) #Аэропорт William B Hartsfield-Atlanta Intl, находится в городе Атланта
 


[('ATL', 414513)]


In [87]:
AirTime_mean = defaultdict(int)
ap_set = set()
for a in data['Origin']:
    ap_set.add(a)

ap_set
    
for a in ap_set:
    tmp = data[data['Origin'] == a]
    AirTime_mean[a] = np.mean(tmp['AirTime'])

#AirTime_mean
    
max(AirTime_mean.iterkeys(), key=(lambda key: AirTime_mean[key]))  #SJU = Luis Munoz Marin International в San Juan
  


'SJU'

In [89]:
aps = defaultdict(int) 
for a in ap_set:
    aps[a] = len(data[data['Origin'] == a])


aps = filter(lambda x: aps[x] >= 1000, aps)
aps_delay_rate = defaultdict(float)
for a in aps:
    tmp = sub_data[data['Origin'] == a]
    if (len(tmp) == 0):
        continue
    aps_delay_rate[a] = sum(tmp['DepDelay'] > 0)/float(len(tmp))

max(aps_delay_rate.iterkeys(), key=(lambda key: aps_delay_rate[key]))   #SLC = Salt Lake City Intl, City = Salt Lake City 


'SLC'

In [82]:
?set